name: C++ Test With Output Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        compiler: g++ 
        cmake-version: 3.20

    - name: Build and run tests
      run: |
        chmod +x test.sh
        ./test.sh

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: output.txt
