name: C++ Test With Output Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build and run tests
      run: |
        chmod +x test.sh
        ./test.sh
    
